### ISSUE TITLE
can't import from estuary client

### ISSUE THREAD

**Issue by snissn** [application-research/pestuary#21]
from estuary_client import UtilContentAddIpfsBody 

i think this is now TypesIpfsPin

failing

ImportError: cannot import name 'MainCreateCollectionBody' from 'estuary_client' (/opt/homebrew/lib/python3.10/site-packages/estuary_client/__init__.py)

i think when we upgrade estuary_clients from v2 to v3 we created some issues
